@startuml
'https://plantuml.com/component-diagram


package "Main Area" {
  component contacts [
  Contact information
  ==
  --
  Buttons
  --
  add section

  Inputs
  --
  Photo - media

  ]

  component about [
  Summary or About
  ]

  component skills [
  Skills
  ]

  component projects [
  Projects
  ]

  component experience [
  Work experience
  ==
  --
  Buttons
  --
  add section
  save section
  cancel section
  delete section

  --
  Input fields:
  --
  Title - text
  Employment type - options
  Company name - text
  Location - text
  Type of contract - options
  I am currently working - checkbox
  Start date - date
  End date - date :hidden if currently working checked
  Description - textarea
  skills keywords - component
  ]

  component education [
  Education
  ]

  component additional [
  Additional information
  ]

  contacts --> about
  about --> skills
  skills --> projects
  projects --> experience
  experience --> education
  education --> additional
}



package "Manage Area" {
component cvList [
...list of saved resumes
]

component btns [
edit delete
]

cvList --> btns
}
@enduml
